### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Altoholic** [DomenikIrrgang/ClassicLFG#123]
Message: ...\AddOns\ClassicLFG\src\gui\widgets\dropdown-menu.lua:166: attempt to index field '?' (a nil value)
Time: Sun Mar  1 08:38:20 2020
Count: 1
Stack: ...\AddOns\ClassicLFG\src\gui\widgets\dropdown-menu.lua:166: attempt to index field '?' (a nil value)
...\AddOns\ClassicLFG\src\gui\widgets\dropdown-menu.lua:166: in function `SetItems'
...face\AddOns\ClassicLFG\src\gui\settings\settings.lua:7: in function <...face\AddOns\ClassicLFG\src\gui\settings\settings.lua:6>
[C]: in function `Show'
...ace\AddOns\ClassicLFG\src\gui\widgets\tab-button.lua:69: in function `Select'
...ace\AddOns\ClassicLFG\src\gui\widgets\tab-button.lua:58: in function `OnClick'
...ace\AddOns\ClassicLFG\src\gui\widgets\tab-button.lua:49: in function <...ace\AddOns\ClassicLFG\src\gui\widgets\tab-button.lua:47>

Locals: self = <table> {
 DefaultText = "Select Broadcast channel"
 Disabled = false
 SelectedItems = <table> {
 }
 Open = false
 Entries = <table> {
 }
 Items = <table> {
 }
 OnValueChanged = <function> defined @Interface\AddOns\ClassicLFG\src\gui\settings\settings.lua:18
 DeselectAllEntry = <table> {
 }
 Frame = <unnamed> {
 }
 SelectAllEntry = <table> {
 }
 MultiSelect = false
}
items = <table> {
}
i = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "TOPLEFT"
(*temporary) = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = <table> {
 Active = false
 Id = 30
 Frame = <unnamed> {
 }
 Selected = false
 Text = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by DomenikIrrgang** [comment]
Should be fixed with the newest release :)

**Comment by tordenflesk** [comment]
Still an issue on TBC classic:

6x ClassicLFG\src\gui\widgets\dropdown-menu.lua:166: attempt to index field '?' (a nil value)
[string "@ClassicLFG\src\gui\widgets\dropdown-menu.lua"]:166: in function `SetItems'
[string "@ClassicLFG\src\gui\settings\settings-Settings.lua"]:7: in function <...faceClassicLFG\src\gui\settings\settings.lua:6>
[string "=[C]"]: in function `Show'
[string "@ClassicLFG\src\gui\widgets\tab-button.lua"]:69: in function `Select'
[string "@ClassicLFG\src\gui\widgets\tab-button.lua"]:58: in function `OnClick'
[string "@ClassicLFG\src\gui\widgets\tab-button.lua"]:49: in function <...aceClassicLFG\src\gui\widgets\tab-button.lua:47>

Locals:
self = <table> {
 DefaultText = "Select Broadcast channel"
 Disabled = false
 SelectedItems = <table> {
 }
 Open = false
 Entries = <table> {
 }
 Items = <table> {
 }
 OnValueChanged = <function> defined @ClassicLFG\src\gui\settings\settings.lua:18
 DeselectAllEntry = <table> {
 }
 Frame = <unnamed> {
 }
 SelectAllEntry = <table> {
 }
 MultiSelect = false
}
items = <table> {
}
i = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
 PixelSnapDisabled = true
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:239
 Center = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:477
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:301
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:269
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:365
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:509
 RightEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 BottomEdge = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:275
 BottomLeftCorner = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:381
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:416
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:369
 TopRightCorner = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:496
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:434
 TopLeftCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:333
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:486
 LeftEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:353
}
(*temporary) = "TOPLEFT"
(*temporary) = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = <table> {
 Active = false
 Id = 30
 Frame = <unnamed> {
 }
 Selected = false
 Text = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
